const express = require("express");
const ctrl = require("../../controllers/notices");
const { validateBody, isValidId, authenticate } = require("../../middlewares");
const { ctrlWrapper } = require("../../helpers");
const router = express.Router();
router.get("/category/:categoryName", ctrlWrapper(ctrl.getNoticesByCategory));
router.get("/own", authenticate, ctrlWrapper(ctrl.getOwnerNotices));
router.get("/:categoryName/:noticeId", ctrlWrapper(ctrl.getNoticeById));
router.post("/", authenticate, ctrlWrapper(ctrl.addNotice));
module.exports = router;
